In [15]:
import pandas as pd
df = pd.read_csv('forum2.csv')
df

,이메일 주소,성함,소속,직위,연락처(010-1234-5678),포럼 참가 목적
0,002156@kcu.ac.kr,이경미,KC대학교,직원,1096940030,NaN
1,002157@kcu.ac.kr,강태희,교수학습지원센터,직원,010-4101-7933,NaN
2,002157@kcu.ac.kr,강태희,KC대학교 교수학습지원센터,직원,010-4101-7933,NaN
3,002192@kcu.ac.kr,이열매,KC대학교 교수학습지원센터,직원,010-3448-8881,직무향상
4,00rudi@hanmail.net,박영미,경북전문대학교,조교수,010-7768-8846,NaN
...,...,...,...,...,...,...
3373,zyjung@kpc.or.kr,정지영,한국생산성본부,전문위원,010-4322-4001,NaN
3374,zzanggu0591@naver.com,노정철,함현초,교사,010-8860-4191,학습
3375,zziyeons@gmail.com,정지연,한양대학교,석사과정,010-9920-5793,메타버스 활용 사례가 궁금해서
3376,zzommi@chunjae.co.kr,조은미,천재교과서,과장,010-3287-6933,교과서 개발 시 참고용
3377,zzommi@chunjae.co.kr,조은미,천재교과서,팀원,NaN,NaN

In [16]:
df.drop_duplicates(['이메일 주소'], inplace=True, ignore_index=True)
df.to_excel('포럼 명단_21.01.06.xls', 'w')

<ipython-input-16-5a1d1f1f5497>:2: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  df.to_excel('포럼 명단_21.01.06.xls', 'w')